Booker/config/routes.rb
Rails.application.routes.draw do


 
  devise_for :users

 root to: 'home#start'
 get 'search' => 'search#search'
 get 'home/about' => 'home#about' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:create, :index, :show, :edit, :destroy ,:update] do
   resource :favorites, only:[:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
   end
   resources :users, only:[:show, :index, :edit, :update]
   
   
   resources :users do
    member do
      get :following
      get :followers
    end
  end
  
   resources :relationships, only: [:create, :destroy,:index]

end

Booker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Booker/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
     def self.search_method(search,word)
        if search == 'forward_match'
             @book = Book.where(['title like ?', "#{word}%"])
        elsif search == 'backward_match'
             @book = Book.where(['title like ?', "%#{word}"])
        elsif search == 'perfect_match'
             @book = Book.where(title: word)
        elsif search == 'partial_match'
             @book = Book.where(['title like ?',"%#{word}%"])
        else
             @book = Book.all
        end
     end

  
 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }
end

Booker/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true  
end

Booker/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
end

Booker/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to:follower, class_name: "User"
  belongs_to:followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
     
    #   add_index :relationships, :follower_id
    # add_index :relationships, :followed_id
    # add_index :relationships, [:follower_id, :followed_id], unique: true
end

Booker/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2 , maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
  def self.search_user(search,word)
      if search == "forward_match"
          @user = User.where(["name LIKE?","#{word}%"])
      elsif search == "backward_match"
           @user = User.where(["name LIKE?","%#{word}"])
      elsif search == "perfect_match"
          @user = User.where(name:"word")
      elsif search == "partial_match"
          @user = User.where(["name LIKE?","%#{word}%"])
      else
           User.all
      end
  end
     # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)

    # self.active_relationships.create(followed_id: other_user.id)

    # current_user.follow(@user)
    # current_user.active_relationships.create(followed_id: @user.id)
    # Relationsip.create(follower_id: urrent_user.id, followed_id: @user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
end

Booker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?


 def after_sign_in_path_for(resource)
     user_path (current_user)
 end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])

  end
end

Booker/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save 
      flash[notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id) 
    else
      @books = Book.all
      render :index
    end   
  end

  def index 
    @book =Book.new
    @books = Book.all
    @user = @book.user
    @users= User.all
    
  end 
   
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @book_comment = BookComment.new
    
  end  
  
  def edit
    @book= Book.find(params[:id])
    if current_user != @book.user
    redirect_to books_path
    end
  end  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path 
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully update.'
    else
    render :edit
    end
  end
  
   
  
  
  
  private

   def book_params
    params.require(:book).permit(:title,:body)
   end
   
end

Booker/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

Booker/app/controllers/home_controller.rb
class HomeController < ApplicationController
   
  def start
  end
  
  def about
  end
end

Booker/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
        @range = params[:range]
        search = params[:search]
        word = params[:word]
        if @range == '1'
            @user = User.search_user(search,word)
        else
             #@book = Book.where('title like ?', '初投稿%')
           @book = Book.search_method(search,word)
        end
  end
end

Booker/app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!


 def edit
    @user = User.find(params[:id])
    if current_user != @user
    redirect_to user_path(current_user)
    end
 end

 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
  redirect_to user_path(@user.id), notice:'You have updated user successfully.'
  else

  render :edit
  end
 end

 def show
  @user = User.find(params[:id])
  @book = Book.new
  @books = @user.books
 end

 def index
 @users = User.all
 @book =Book.new
 @user = current_user
 @relationship = current_user.active_relationships.find_by(followed_id: @user.id) 
 end

  def following
    @book  = Book.new
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render :show_follow
  end

  def followers
    @book = Book.new
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render :show_follow
  end
 

private
 def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
 end

end

Booker/app/helpers/application_helper.rb
module ApplicationHelper
end

Booker/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Booker/app/helpers/books_helper.rb
module BooksHelper
end

Booker/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Booker/app/helpers/home_helper.rb
module HomeHelper
end

Booker/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Booker/app/helpers/search_helper.rb
module SearchHelper
end

Booker/app/helpers/users_helper.rb
module UsersHelper
end

Booker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Bookers</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

  <header class="navbar  navbar-inverse">
  <div class="container">

    <nav class="nav navbar-nav navbar-left">
    <span>Bookers</span>
      </li>

    </nav>

    <nav>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>

       <li class="">
       <%= link_to" Home", user_path(current_user), class: "glyphicon glyphicon-home"  %>
       </li>

       <li class="">
         <%= link_to" Users", users_path, class: "glyphicon glyphicon-user"  %>

       </li>

      <li class="">
        <%= link_to" Books", books_path, class: "glyphicon glyphicon-book" %>
       </li>

      <li class="">
        <%= link_to" logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out"%>
      </li>

      </ul>
    </nav>

    <div id="slidemenu">
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">


    <% else %>

      <li class="">
        <%= link_to ' Home', root_path, class: "glyphicon glyphicon-home"%>
       </li>

       <li class="">
        <%= link_to ' About', home_about_path, class: "glyphicon glyphicon-link" %>
       </li>

      <li class="">
        <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
      </li>
      <li class="">
        <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
      </li>
    <% end %>
  </ul>
</div>

  </header>
</div>

   <% flash.each do |message_type, message| %>
    <%= message %>
    <% end %>
    
    <!--↓検索機能-->
    
    <div class= "container">
      <div class= "row">
        <div class="col-xs-6 col-xs-offset-3">
          <% if user_signed_in? %>
       <%= form_with url:search_path, method: :get, data: {remote: false},html: {class:"form-inline"} do |f| %>
           
           <div class="form-group">
           <%= f.text_field :word %>
           </div>
           
           <div class="form-group">
           <%= f.select :range, {'User': '1', 'Book': '2'}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
           </div>
           
           <div class="form-group">
             <%= f.select :search, {"前方一致": "forward_match", "後方一致": "backward_match", "部分一致":"partial_match","完全一致": "perfect_match" }, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
           </div>
           <div class="form-group">
           <button type="submit" class="btn btn-primary btn-block">検索</button>
           </div>
          <% end %>
         <% end %>
       
      </div>
    </div>
    </div>
<!--終了-->

   <%= yield %>
  <footer>
    <div class= "container">
      <div class= "row">
        <div class= "col-xs-3 col-xs-offset-9">
      <p>CoppyRight Infratop.inc</p>
      </div>
      </div>
      </div>
  </footer>

  </body>
</html>

Booker/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>