Booker/config/routes.rb
Rails.application.routes.draw do


 
  devise_for :users

 root to: 'home#start'
 get 'search' => 'search#search'
 get 'home/about' => 'home#about' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:create, :index, :show, :edit, :destroy ,:update] do
   resource :favorites, only:[:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
   end
   resources :users, only:[:show, :index, :edit, :update]
   
   
   resources :users do
    member do
      get :following
      get :followers
    end
  end
  
   resources :relationships, only: [:create, :destroy,:index]

end

Booker/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
     def self.search_method(search,word)
        if search == 'forward_match'
             @book = Book.where(['title like ?', "#{word}%"])
        elsif search == 'backward_match'
             @book = Book.where(['title like ?', "%#{word}"])
        elsif search == 'perfect_match'
             @book = Book.where(title: word)
        elsif search == 'partial_match'
             @book = Book.where(['title like ?',"%#{word}%"])
        else
             @book = Book.all
        end
     end

  
 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }
end

Booker/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save 
      flash[notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id) 
    else
      @books = Book.all
      render :index
    end   
  end

  def index 
    @book =Book.new
    @books = Book.all
    @user = @book.user
    @users= User.all
    
  end 
   
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @book_comment = BookComment.new
    
  end  
  
  def edit
    @book= Book.find(params[:id])
    if current_user != @book.user
    redirect_to books_path
    end
  end  
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path 
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully update.'
    else
    render :edit
    end
  end
  
   
  
  
  
  private

   def book_params
    params.require(:book).permit(:title,:body)
   end
   
end

Booker/app/helpers/books_helper.rb
module BooksHelper
end

Booker/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@book, local: true do |f| %>

<% if @book.errors.any? %>
    
  <div class="alert-warning">
    <div class="alert1">
      <p><%= pluralize(@book.errors.count, "error") %></p>
    </div
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
      <%= f.label :title %></br>
      <%= f.text_field :title %>
 
  </div>
 
<div class ="field">
    <%= f.label :opnion %></br>
    <%= f.text_area :body%> 
</div>

<div class ="actions">
    <%= f.submit 'Update Book' %>
</div>
 <% end %>

<%= link_to 'Show', book_path %>
|
  <%= link_to 'Back', books_path %>
  

Booker/app/views/books/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
 

  <%= attachment_image_tag current_user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>
  
  <table class="table">
    <tbody>
  <tr>
    <th>name</th>
    <th class="profile-name"><%= current_user.name %></th>
  </tr>
  <tr>
   <th>introduction</th>
   <th><%= current_user.introduction %></th>
   </tr>
   <tr>
     <th>follows</th>
     <th>
       <% @user ||= current_user %>
     <%= link_to @user.following.count,following_user_path(@user) %>

   </th>
   </tr>
   <tr>
     <th>followers</th>
     <th>
       <% @user ||= current_user %>
       <%= link_to @user.followers.count,followers_user_path(@user) %>
</tbody>
</table>

<% if  @user == current_user %>
  <%= link_to"", edit_user_path(current_user), class: "btn btn-default btn-block glyphicon glyphicon-wrench"  %>
  <% end %>

<h2>New book </h2>

<% if @book.errors.any? %>
    
  <div class="alert-warning">
    <div class="alert1">
    <p><%= pluralize(@book.errors.count, "error") %></p>
    </div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= form_with model: @book,  local:true do |f| %>
  
  
  <div class="form-group">
      <%= f.label :title %></br>
      <%= f.text_field :title, class: 'form-control' %>
  </div>

<div class ="form-group">
    <%= f.label :opnion %></br>
    <%= f.text_area :body, class: 'form-control' %>
</div>
<div class ="form-group">
 <button type="submit" class="btn btn-primary btn-block">Create Book</button>
</div>
<% end %>
 </div>



<div class="col-xs-9">
  
 
 <table class=table>
   <h1>Books</h1>
  <thead>
  <tr>
   <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th></th>
  </tr>
  </thead>
  
  <tbody>
      <% @books.each do |book| %>
  <tr>
    
     <td>
    <%= link_to user_path(book.user) do%>
    <%= attachment_image_tag book.user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>
     <% end %>
    </td>
   
    <td>
    <%= link_to book.title,book_path(book) %>
    </td>

    <td>
    <span><%= book.body %></span>
    </td>
    <td>
    <!--↓いいね-->
        <% if book.favorited_by?(current_user) %>
         <div>
         <%= link_to book_favorites_path(book), method: :delete do %>
       
         
			<span class="glyphicon glyphicon-heart" aria-hidden="true" ></span>
         <%= book.favorites.count %>
         <%end%>
         </div>
         <% else %>
         <div>
           <%= link_to book_favorites_path(book), method: :post do %>
     
			<span class="glyphicon glyphicon-heart-empty"></span>
           <%= book.favorites.count %>
           <% end %>
         </div>
         <% end %>
         
         
    
  </td>

    <td>
    <i class="fa fa-comment"></i>
    <a href="#comments">コメント数 :<%= book.book_comments.count %></a>
    </td>
   
  </tr>
  <% end %>
  </tbody>
  </table>
</div>
</div>
</div>

Booker/app/views/books/show.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
 

  <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>
  
  <table class="table">
    <tbody>
  <tr>
    <th>name</th>
    <th class="profile-name"><%= @user.name %></th>
  </tr>
  <tr>
   <th>introduction</th>
   <th><%= @user.introduction %></th>
   </tr>
    <tr>
     <th>follows</th>
     <th>
     <%= link_to @user.following.count,following_user_path(@user) %>

   </th>
   </tr>
   <tr>
     <th>followers</th>
     <th>
       <% @user ||= current_user %>
       <%= link_to @user.followers.count,followers_user_path(@user) %>
</tbody>
</table>
    
    
   <% if  @user == current_user %>
  <%= link_to"", edit_user_path(current_user), class: "btn btn-default btn-block glyphicon glyphicon-wrench"  %>
   <% end %>
  
<h2>New book </h2>

<% if @book.errors.any? %>
    
  <div class="alert-warning">
    <div class="alert1">
    <p><%= pluralize(@book.errors.count, "error") %></p>
    </div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= form_with model: @books,  local:true do |f| %>
  
  
  <div class="form-group">
      <%= f.label :title %></br>
      <%= f.text_field :title, class: 'form-control' %>
  </div>

<div class ="form-group">
    <%= f.label :opnion %></br>
    <%= f.text_area :body, class: 'form-control' %>
</div>
<div class ="form-group">
 <button type="submit" class="btn btn-primary btn-block">Create Book</button>
</div>
<% end %>
 </div>



<div class="col-xs-9">

<table class=table>
  
  <h2>Book detail</h2>
  <thead>

  <tr>
  <th></th>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
  </tr>
  </thead>


  <tbody>
    
  <tr>
    <td>
    <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %><br>
    <%= link_to @user.name,user_path(@user) %>
    </td>
    <td>
    <%= link_to @book.title,book_path(@book) %>
    </td>

    <td>
    <span><%= @book.body %></span>
    </td>
  <td>
    <% if @book.user.id == current_user.id %>
    <%= link_to "Edit", edit_book_path(@book.id) %>
    <% end %>
  </td>
  <td>
  <% if @book.user.id == current_user.id %>
  <%= link_to "Destroy", book_path(@book), method: :delete,"data-confirm" => "本当に消しますか?" %>
  <% end %>
  </td>
  <td>
    <!--↓いいね-->
        <% if @book.favorited_by?(current_user) %>
         <div>
         <%= link_to book_favorites_path(@book), method: :delete do %>
         
			<span class="glyphicon glyphicon-heart" aria-hidden="true" ></span>
         <%= @book.favorites.count %>
         <%end%>
         </div>
         <% else %>
         <div>
           <%= link_to book_favorites_path(@book), method: :post do %>
     
			<span class="glyphicon glyphicon-heart-empty"></span>
           <%= @book.favorites.count %>
           <% end %>
         </div>
         <% end %>
         
         
    
  </td>
  <td>
    
    <i class="fa fa-comment"></i>
    <a href="#comments">コメント数 :<%= @book.book_comments.count %></a>
   
  
  </td>
  </tr>
  </tbody>
  </table>

<table>
  <% @book.book_comments.each do |book_comment| %>
<tbody>
  <tr>
    <td>
    <div class="comment-body bb">
      <div class="comment-avatar">
        <div class="avatar">
          <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>
           <div class="comment-author clearfix">
          <a href="#" class="link-author"><%= book_comment.user.name %></a>
        </div>
        </div>
      </div>
      </div>
      </td>
    <td>
      <div class="comment-text">
       
        <div class="comment-entry"><%= book_comment.comment%></div>
        <%if book_comment.user == current_user %>
        
      </div>
   </td>
   <td>
     <div>
          <%= link_to "Destroy",book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger " %>
        </div>
        <% end %>
   </td>
    
  </tr>
</tbody>
<% end %>
</table>


<%= form_with(model:[@book, @book_comment], local: true)do |f| %>
<div class="row">
  <div class="col-sm-11">
    <%= f.text_area :comment, rows:'5', class: "form-control" %>
  </div>

<%= f.submit "送信",class:"btn btn-lg btn-base1 mt-20 " %>
 <% end %>
</div>


<!--↑がコメントフォーム-->
  </div>
  
  
  </div>
  </div>
  </div>
  
  