Booker/config/routes.rb
Rails.application.routes.draw do


 
  devise_for :users

 root to: 'home#start'
 get 'search' => 'search#search'
 get 'home/about' => 'home#about' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:create, :index, :show, :edit, :destroy ,:update] do
   resource :favorites, only:[:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
   end
   resources :users, only:[:show, :index, :edit, :update]
   
   
   resources :users do
    member do
      get :following
      get :followers
    end
  end
  
   resources :relationships, only: [:create, :destroy,:index]

end

Booker/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2 , maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
  def self.search_user(search,word)
      if search == "forward_match"
          @user = User.where(["name LIKE?","#{word}%"])
      elsif search == "backward_match"
           @user = User.where(["name LIKE?","%#{word}"])
      elsif search == "perfect_match"
          @user = User.where(name:"word")
      elsif search == "partial_match"
          @user = User.where(["name LIKE?","%#{word}%"])
      else
           User.all
      end
  end
     # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)

    # self.active_relationships.create(followed_id: other_user.id)

    # current_user.follow(@user)
    # current_user.active_relationships.create(followed_id: @user.id)
    # Relationsip.create(follower_id: urrent_user.id, followed_id: @user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
end

Booker/app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :authenticate_user!


 def edit
    @user = User.find(params[:id])
    if current_user != @user
    redirect_to user_path(current_user)
    end
 end

 def update
  @user = User.find(params[:id])
  if @user.update(user_params)
  redirect_to user_path(@user.id), notice:'You have updated user successfully.'
  else

  render :edit
  end
 end

 def show
  @user = User.find(params[:id])
  @book = Book.new
  @books = @user.books
 end

 def index
 @users = User.all
 @book =Book.new
 @user = current_user
 @relationship = current_user.active_relationships.find_by(followed_id: @user.id) 
 end

  def following
    @book  = Book.new
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render :show_follow
  end

  def followers
    @book = Book.new
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render :show_follow
  end
 

private
 def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
 end

end

Booker/app/helpers/users_helper.rb
module UsersHelper
end

Booker/app/views/users/_follow.html.erb
<%= form_with url: relationships_path, method: :post do %>
  <%= hidden_field_tag :followed_id, user.id %>
  <%= submit_tag "フォローする", class: "btn btn-success" %>
<% end %>

Booker/app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <div id="follow_form">
    <% if current_user.following?(user) %>
      <%= render 'unfollow', user: user %>
    <% else %>
      <%= render 'follow', user: user %>
    <% end %>
  </div>
<% end %>

Booker/app/views/users/_unfollow.html.erb
<% relationship = current_user.active_relationships.find_by(followed_id: user.id) %>
<%= form_with url: relationship_path(relationship), method: :delete do %>
  <%= submit_tag "フォロー外す", class: "btn-primary" %>
<% end %>

Booker/app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
    
  <div class="alert-warning">
    <div class="alert1">
    <p><%= pluralize(@user.errors.count, "error") %></p>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@user, local:true do |f| %>
  
<div class ="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
</div>
<div class ="field">
    <%= f.label :image %></br>
    <%= f.attachment_field :profile_image %>
</div>
<div class ="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction %>
</div>
 <%= f.submit "Update User" %>
</div>
<% end %>

Booker/app/views/users/index.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
 
    <h2>User info</h2>


  <%= attachment_image_tag current_user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>

  <table class="table">
    <tbody>
  <tr>
    <th>name</th>
    <th class="profile-name"><%= current_user.name %></th>
  </tr>
  <tr>
   <th>introduction</th>
   <th><%= current_user.introduction %></th>
   </tr>
   <tr>
     <th>follows</th>
     <th>
       <% @user ||= current_user %>
     <%= link_to @user.following.count,following_user_path(@user) %>

   </th>
   </tr>
   <tr>
     <th>followers</th>
     <th>
       <% @user ||= current_user %>
       <%= link_to @user.followers.count,followers_user_path(@user) %>
   </tr>
</tbody>
</table>




  <%= link_to"", edit_user_path(current_user), class: "btn btn-default btn-block glyphicon glyphicon-wrench"  %>


<h2>New book </h2>

<% if @book.errors.any? %>

  <div class="alert-warning">
    <div class="alert1">
    <p><%= pluralize(@book.errors.count, "error") %></p>
    </div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= form_with model: @book,  local:true do |f| %>


  <div class="form-group">
      <%= f.label :title %></br>
      <%= f.text_field :title, class: 'form-control' %>
  </div>

<div class ="form-group">
    <%= f.label :opnion %></br>
    <%= f.text_area :body, class: 'form-control' %>
</div>
<div class ="form-group">
 <button type="submit" class="btn btn-primary btn-block">Create Book</button>
</div>
<% end %>
 </div>

<div class="col-xs-9">


 <table class=table>
   <h1>Users</h1>
  <thead>
  <tr>
   <th>image</th>
   <th>name<th>
   <th></th>
  </tr>
  </thead>

  <tbody>
      <% @users.each do |user| %>
  <tr>

     <td>
     <%= attachment_image_tag user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>
    </td>
    <td>
    <%= user.name  %>
    </td>
    <t
      フォロー数: <%= user.following.count %>

   </th>
    <td>
      フォローワー数: <%= user.followers.count %>
    </td>
    <td>
      <%= render 'follow_form', user: user %>

    </td>
    <td>
    <span><%= link_to "Show",user_path(user) %></span>
    </td>


  </tr>
  <% end %>
  </tbody>
  </table>
</div>
</div>
</div>

Booker/app/views/users/show.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>


  <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>

  <table class="table">
    <tbody>
  <tr>
    <th>name</th>
    <th class="profile-name"><%= @user.name %></th>
  </tr>
  <tr>
   <th>introduction</th>
   <th><%= @user.introduction %></th>
   </tr>
    <tr>
     <th>follows</th>
     <th>
     <%= link_to @user.following.count,following_user_path(@user) %>

   </th>
   </tr>
   <tr>
     <th>followers</th>
     <th>
       <% @user ||= current_user %>
       <%= link_to @user.followers.count,followers_user_path(@user) %>

   </th>
   </tr>
</tbody>
</table>

<!--フォロー、フォロワー機能↓-->

<%= render 'follow_form', user: @user %>
<!--ここまで-->

 <% if  @user == current_user %>
  <%= link_to"", edit_user_path(current_user), class: "btn btn-default btn-block glyphicon glyphicon-wrench"  %>
  <% end %>

<h2>New book </h2>

<% if @book.errors.any? %>

  <div class="alert-warning">
    <div class="alert1">
    <p><%= pluralize(@book.errors.count, "error") %></p>
    </div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= form_with model: @book,  local:true do |f| %>


  <div class="form-group">
      <%= f.label :title %></br>
      <%= f.text_field :title, class: 'form-control' %>


  </div>

<div class ="form-group">
    <%= f.label :opnion %></br>
    <%= f.text_area :body, class: 'form-control' %>
</div>
<div class ="form-group">
 <button type="submit" class="btn btn-primary btn-block">Create Book</button>
</div>
<% end %>
 </div>



<div class="col-xs-9">

<table class=table>

  <h2>Books</h2>
  <thead>

  <tr>
    <th></th>
   <th>Title</th>
   <th>Opinion</th>
  </tr>
  </thead>


  <tbody>
      <% @books.each do |book| %>
  <tr>

    <td>

    <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>

    </td>
    <td>

    <span><%= link_to book.title,book_path(book) %></span>
    </td>

    <td>
    <span><%= book.body %></span>
    </td>
    <td>
    <i class="fa fa-comment"></i>
    <a href="#comments">コメント数 :<%= @book.book_comments.count %></a>
    </td>

  </tr>
  <% end %>
  </tbody>
  </table>

  </div>
  </div>
  </div>

Booker/app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>

      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th class="profile-name"><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th> <% @user ||= current_user %>
     <%= link_to @user.following.count,following_user_path(@user) %>
            </th>
          </tr>
         <tr>
            <th>followers</th>
            <th> <% @user ||= current_user %>
       <%= link_to @user.followers.count,followers_user_path(@user) %>
           </th>
         </tr>
        </tbody>
        </table>
        <%= render 'follow_form', user: @user %>
         <% if  @user == current_user %>
      <%= link_to"", edit_user_path(current_user), class: "btn btn-default btn-block glyphicon glyphicon-wrench"  %>
         <% end %>
      <h2>New book </h2>

      <% if @book.errors.any? %>
        <div class="alert-warning">
          <div class="alert1">
          <p><%= pluralize(@book.errors.count, "error") %></p>
          </div>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <%= form_with model: @book,  local:true do |f| %>
        <div class="form-group">
            <%= f.label :title %></br>
            <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class ="form-group">
            <%= f.label :opnion %></br>
            <%= f.text_area :body, class: 'form-control' %>
        </div>

        <div class ="form-group">
          <button type="submit" class="btn btn-primary btn-block">Create Book</button>
        </div>
      <% end %>
    </div>

    <div class="col-xs-9">
      <h1><%= @title %></h1>
      <table class=table>
        <thead>
          <tr>
            <th>image</th>
            <th>name<th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %>
              </td>
              <td>
                <%= user.name  %>
              </td>
              <td>
                <span><%= link_to "Show",user_path(user) %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>